# Generated by Django 3.2.9 on 2021-11-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='blogpost_content',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='blogpost_title',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
